server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false
  rabbitmq: #消息队列配置
    host: 192.168.116.88    #地址
    virtual-host: /leyou   #虚拟主机
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE  #交换机+名字

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期