server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.116.88
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
#拦截用
leyou:
  jwt:
    pubKeyPath:  F:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
ribbon:
  eureka:
    enabled: true